[package]
name = "nostd-entrypoint-invoke"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-nostd-entrypoint.workspace = true
solana-program-entrypoint.workspace = true
solana-program-error.workspace = true

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = [
    'cfg(target_os, values("solana"))',
] }
